config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    resources :consultations, only: [:new, :create, :edit, :update]
  end

  resources :sections, only: [:index, :new, :create, :show, :edit, :update] do
    resources :questions, only: [:new, :create, :edit, :update, :show]
  end
end

app/views/shared/_breadcrumbs.html.erb
<div class="container pt-3">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "  >  " %>
  </ol>
</div>

app/views/shared/_consultation_form.html.erb
<% if (defined?(patient) && patient) && (defined?(consultation)) %>
  <%= simple_form_for [patient, consultation] do |f| %>
  <%= f.input :notes_before, as: :rich_text_area, :input_html => { style: 'height: 60vh' }  %>
  <%= f.input :notes_after, as: :rich_text_area, :input_html => { style: 'height: 60vh' } %>
  <%= f.input :notes_to_send, as: :rich_text_area, :input_html => { style: 'height: 60vh' } %>
  <div class="pb-5">
  <% if policy(consultation).public_send("#{action}?") %>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <% if defined?(path) && path %>
      <%= link_to path do %>
        <button type="button" class="btn btn-primary">Cancel</button>
      <% end  %>
    <% end  %>
  <% end %>
  </div>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-infinito.png" %>
    <% end %>

    <h2 class="titular">Infinito - Admin</h2>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <a class="user dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
              AS
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "Patients", patients_path, class: "dropdown-item" %>
              <%= link_to "Sections", sections_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_patient_form.html.erb
<% if defined?(patient) && patient %>
  <%= simple_form_for patient do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :birthdate, as: :date, html5: true,
                start_year: Date.today.year - 90,
                end_year: Date.today.year - 12,
                discard_day: true,
                order: [:month, :year] %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :dni %>
    <%= f.input :address %>
    <div class="pb-5">
    <% if defined?(action) && action %>
      <% if policy(patient).public_send("#{action}?") %>
        <%= f.button :submit, 'Save', class:'btn btn-primary' %>
        <% if defined?(path) && path %>
          <%= link_to public_send("#{path}") do %>
            <button type="button" class="btn btn-primary">Cancel</button>
          <% end  %>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_patient_header.html.erb
<thead>
  <tr>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Phone</th>
    <th scope="col">Birthdate</th>
    <th scope="col">Address</th>
    <th scope="col">Email</th>
    <th scope="col">DNI</th>
  </tr>
</thead>

app/views/shared/_patient_info.html.erb
<% if defined?(patient) && patient %>
  <td><%= patient.first_name %></td>
  <td><%= patient.last_name %></td>
  <td><%= patient.phone %></td>
  <td><%= patient.birthdate %></td>
  <td><%= patient.address %></td>
  <td><%= patient.email %></td>
  <td><%= patient.dni %></td>
<% end %>

app/views/shared/_question_form.html.erb
<% if (defined?(section) && section) && (defined?(question)) %>
  <%= simple_form_for [section, question] do |f| %>
  <%= f.input :title %>
  <%= f.input :title_to_display %>
  <%= f.input :order %>
  <div class="pb-5">
  <% if policy(question).public_send("#{action}?") %>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <% if defined?(path) && path %>
      <%= link_to path do %>
        <button type="button" class="btn btn-primary">Cancel</button>
      <% end  %>
    <% end  %>
  <% end %>
  </div>
  <% end %>
<% end %>

app/views/shared/_section_form.html.erb
<% if defined?(section) && section %>
  <%= simple_form_for [section] do |f| %>
    <%= f.input :title %>
    <%= f.input :title_to_display %>
    <%= f.input :order %>
    <%= f.association :section %>
    <div class="pb-5">
    <% if defined?(action) && action %>
      <% if policy(section).public_send("#{action}?") %>
        <%= f.button :submit, 'Save', class:'btn btn-primary' %>
        <% if defined?(path) && path %>
          <%= link_to public_send("#{path}") do %>
            <button type="button" class="btn btn-primary">Cancel</button>
          <% end  %>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>
<% end %>