config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    resources :consultations, only: [:new, :create, :edit, :update]
  end

  resources :sections, only: [:index, :new, :create, :show, :edit, :update] do
    resources :questions, only: [:new, :create, :edit, :update, :show]
  end
end

app/models/section.rb
class Section < ApplicationRecord
  validates :title, presence: true, allow_blank: false
  validates :title_to_display, presence: true, allow_blank: false
  validates :order, presence: true, allow_blank: false, numericality: { only_integer: true }
  has_many :questions, -> { order(order: :asc) }
  has_many :sections, -> { order(order: :asc) }, dependent: :destroy
  belongs_to :section, optional: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[show edit update]
  before_action :set_breadcrumbs, only: %i[index show new edit]

  def index
    # authorize @sections = policy_scope(Section).includes(:sections, :questions).all.order(:order, :created_at, :section_id)
    # authorize @sections = policy_scope(Section).joins(:sections).includes(:sections, :questions).all.order(:order)
    # authorize @sections = policy_scope(Section).left_joins(:sections).distinct.all.order(section_id: :desc).order(:order)
    authorize @sections = policy_scope(Section).includes(:sections, :questions).all.order(:order)

    # .left_joins(:sections).where(sections: { section_id: !nil })
  end

  def new
    authorize @section = Section.new
  end

  def create
    authorize @section = Section.new(section_params)
    parent = Section.find(params["section"]["section_id"].to_i) unless params["section"]["section_id"].empty?
    @section.section = parent if parent
    if @section.save
      redirect_to sections_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    parent = params["section"]["section_id"]
    parent.empty? ? parent = nil : parent = Section.find(params["section"]["section_id"].to_i)
    @section.section = parent
    if @section.update(section_params)
      redirect_to sections_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def section_params
    params.require(:section).permit(:title, :title_to_display, :order)
  end

  def set_section
    authorize @section = Section.find(params[:id])
  end

  def set_breadcrumbs
    add_breadcrumb "Home", '/'
    add_breadcrumb "Sections", sections_path
    add_breadcrumb "New", new_section_path if action_name == 'new'
    # add_breadcrumb "Patient details", "/patients/#{@patient.id}" if action_name == 'show' || action_name == 'edit'
    add_breadcrumb "Edit details", "/sections/#{@section.id}/edit" if action_name == 'edit'
  end
end

app/views/sections/edit.html.erb
<div class="container pt-5">
  <div class="row mt-3">
    <div class="col-3 text-start">
      <h1>Edit Section</h1>
    </div>
    <div class="text-end">
      <%= link_to new_section_question_path(@section) do %>
        <button type="button" class="btn btn-primary">Add Question</button>
      <% end  %>
    </div>
  </div>
  <%= render "shared/section_form", section: @section, action: 'update', path: 'sections_path' %>
</div>

app/views/sections/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col">
      <h1>Anamnesis</h1>
    </div>
    <div class="col text-end">
    <%= link_to new_section_path do %>
      <button type="button" class="btn btn-primary">New Section</button>
     <% end  %>
    </div>
  </div>
  <div class="accordion" id="accordionSections">
    <% @sections.each do |section|  %>

      <% if section.section.nil? %>
        <%# Section %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="title-<%= section.id %>">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSection<%= section.id %>" aria-expanded="true" aria-controls="collapseSection<%= section.id %>">
              <% if section.section.nil? %>
                <%= section.order %> - <%= section.title %>
              <% else %>
                <%= section.section.order %>.<%= section.order %> - <%= section.title %>
              <% end %>
              <div class="ms-3 text-left">
                <%= link_to edit_section_path(section) do %>
                  <i class="fa-solid fa-pen-to-square"></i></i>
                <% end  %>
              </div>
              <div class="ms-3 text-left">
                <%= link_to section_path(section) do %>
                  <i class="fa fa-eye" aria-hidden="true"></i>
                <% end  %>
              </div>
            </button>
          </h2>
          <%# Collapse layer for Section %>
          <div id="collapseSection<%= section.id %>" class="accordion-collapse collapse show" aria-labelledby="title-<%= section.id %>" data-bs-parent="#accordionSections">
            <div class="accordion-body">

              <%# list of questions for the section  %>
              <div class="list-group">
                <% if !section.questions.empty? %>
                  <% section.questions.each do |question|  %>
                    <%= link_to edit_section_question_path(section, question), class: "list-group-item list-group-item-action" do %>
                      <%= question.order %>. <%= question.title %>
                      <i class="fa-solid fa-pen-to-square ms-3"></i>
                    <% end  %>
                  <% end %>
                <% end %>
              </div>

            <%# Subsections? %>
            <% if !section.sections.empty? %>
              <% section.sections.each do |section|  %>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="title-<%= section.id %>">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSection<%= section.id %>" aria-expanded="true" aria-controls="collapseSection<%= section.id %>">
                      <% if section.section.nil? %>
                        <%= section.order %> - <%= section.title %>
                      <% else %>
                        <%= section.section.order %>.<%= section.order %> - <%= section.title %>
                      <% end %>
                      <div class="ms-3 text-left">
                        <%= link_to edit_section_path(section) do %>
                          <i class="fa-solid fa-pen-to-square"></i></i>
                        <% end  %>
                      </div>
                      <div class="ms-3 text-left">
                        <%= link_to section_path(section) do %>
                          <i class="fa fa-eye" aria-hidden="true"></i>
                        <% end  %>
                      </div>
                    </button>
                  </h2>
                  <div id="collapseSection<%= section.id %>" class="accordion-collapse collapse show" aria-labelledby="title-<%= section.id %>" data-bs-parent="#accordionSections">
                    <div class="accordion-body">

                      <div class="list-group">
                        <% if !section.questions.empty? %>
                          <% section.questions.each do |question|  %>
                            <%= link_to edit_section_question_path(section, question), class: "list-group-item list-group-item-action" do %>
                              <%= question.order %>. <%= question.title %>
                              <i class="fa-solid fa-pen-to-square ms-3"></i>
                            <% end  %>
                          <% end %>
                        <% end %>
                      </div>

                    </div>
                  </div>
              </div>

              <% end %>
            <% end %>
            </div>
          </div>

        </div>

      <% end %>

    <% end %>
  </div>
</div>

app/views/sections/new.html.erb
<div class="container pt-5">
  <div class="row mt-3">
    <h1>New Section</h1>
  </div>
  <%= render "shared/section_form", section: @section, action: 'create', path: 'sections_path' %>
</div>

app/views/sections/show.html.erb
<div class="container">
  <div class="row mt-3 align-items-center">
      <div class="col-3 pt-3">
        <h1>Section details</h1>
      </div>
      <div class="col-3 text-left">
        <%= link_to edit_section_path(@section) do %>
          <i class="fa-solid fa-pen-to-square"></i></i>
        <% end  %>
      </div>
      <div class="col-6 text-end">
        <%= link_to new_section_question_path(@section) do %>
          <button type="button" class="btn btn-primary">Add Question</button>
        <% end  %>
      </div>
    </div>
  </div>
</div>