config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    resources :consultations, only: [:new, :create, :edit, :update]
  end

  resources :sections, only: [:index, :new, :create, :show, :edit, :update] do
    resources :questions, only: [:new, :create, :edit, :update, :show]
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :consultations, dependent: :destroy
  validates :first_name, presence: true, allow_blank: false
  validates :last_name, presence: true, allow_blank: false
  has_one :quiz, dependent: :destroy
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update]
  before_action :set_breadcrumbs, only: %i[index show new edit]

  def index
    if params[:query].present?
      authorize @patients = policy_scope(Patient.where("first_name ILIKE ?", "#{params[:query]}%").page params[:page])
    else
      authorize @patients = policy_scope((Patient.all.order("created_at DESC").page params[:page]))
    end
  end

  def show
    authorize @consultations = @patient.consultations.
                                        includes([:rich_text_notes_before]).
                                        includes([:rich_text_notes_after]).
                                        includes([:rich_text_notes_to_send]).
                                        all.order("date DESC")
  end

  def new
    authorize @patient = Patient.new
  end

  def create
    authorize @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patient_path(@patient)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path(@patient)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :birthdate, :phone, :address, :email, :dni)
  end

  def set_patient
    authorize @patient = Patient.find(params[:id])
  end

  def set_breadcrumbs
    add_breadcrumb "Home", '/'
    add_breadcrumb "Patients", patients_path
    add_breadcrumb "New", new_patient_path if action_name == 'new'
    add_breadcrumb "Patient details", "/patients/#{@patient.id}" if action_name == 'show' || action_name == 'edit'
    add_breadcrumb "Edit details", "/patients/#{@patient.id}/edit" if action_name == 'edit'
  end
end

app/views/patients/edit.html.erb
<div class="container pt-5" data-search-target='query' data-controller='search'>
  <div class="row mt-3">
    <h1>Edit Patient</h1>
  </div>
  <%= render "shared/patient_form", patient: @patient, action: 'update', path: 'patient_path' %>
</div>

app/views/patients/index.html.erb
<div class="container pt-5 bg-light">
  <div class="row bg-light" >
    <div class="col">
      <h1 class="page-header ">Patients</h1>
    </div>
    <div class="col">
      <%= form_with url: patients_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a patient"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col text-end">
    <%= link_to new_patient_path do %>
      <button type="button" class="btn btn-primary">New Patient</button>
     <% end  %>
    </div>
  </div>
  <table class="table mt-3 table-light table-striped table-hover">
    <%= render "shared/patient_header" %>
    <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <%= render "shared/patient_info", patient: patient %>
        <td>
          <%= link_to patient_path(patient) do %>
          <i class="fa fa-eye" aria-hidden="true"></i>
          <% end  %>
        </td>
        <td>
          <%= link_to edit_patient_path(patient) do %>
          <i class="fa-solid fa-pen-to-square"></i></i>
          <% end  %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row custom-pagination">
    <%= paginate @patients, window: 2 %>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container pt-5">
  <div class="row mt-3">
    <h1>New Patient</h1>
  </div>
  <%= render "shared/patient_form", patient: @patient, action: 'create', path: 'patients_path' %>
</div>

app/views/patients/show.html.erb
<div class="container">
  <div class="row mt-3 align-items-center">
    <div class="col-3 pt-3">
      <h1>Patient details</h1>
    </div>
    <div class="col-3 text-left">
      <%= link_to edit_patient_path(@patient) do %>
        <i class="fa-solid fa-pen-to-square"></i></i>
      <% end  %>
    </div>
    <div class="col-6 text-end">
    <%= link_to new_patient_consultation_path(@patient) do %>
      <button type="button" class="btn btn-primary">New Consultation</button>
     <% end  %>
    </div>
  </div>
  <table class="table mt-4 table-light table-striped table-bordered">
      <%= render "shared/patient_header" %>
    <tbody>
      <tr>
        <%= render "shared/patient_info", patient: @patient %>
      </tr>
    </tbody>
  </table>
  <% if @consultations.empty? %>
  <div class="row pt-3">
    <h2 class="pb-3">No Consultations for this patient yet</h2>
  </div>
  <% end  %>
  <% if !@consultations.empty? %>
  <div class="row pt-3">
    <h2 class="pb-3">Consultations</h2>
  </div>
  <div class="container">
    <% @consultations.each do |consultation|  %>
      <div class="row">
        <p class="text-center fs-5">
          <a href="#" class="text-decoration-none link-secondary"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseConsultationsInfo-<%= consultation.id %>"
                      aria-expanded="false"
                      aria-controls="collapseExample">
                      Date: <%= consultation.date %> <i class="fa-sharp fa-solid fa-caret-down"></i>
          </a>
        </p>
        <hr>
      </div>
      <div class="collapse" id="collapseConsultationsInfo-<%= consultation.id %>">
        <p class="d-inline-block">Last update: <%= consultation.updated_at %></p>
        <%= link_to edit_patient_consultation_path(@patient, consultation) do %>
          <i class="fa-solid fa-pen-to-square"></i></i>
        <% end  %>
        <div class="row pt-3">
          <p><strong>Notes before: </strong></p>
          <p>
            <%= consultation.notes_before %>
          </p>
        </div>
        <div class="row pt-3">
          <p><strong>Notes after: </strong></p>
          <p>
            <%= consultation.notes_after %>
          </p>
        </div>
        <div class="row pt-3">
          <p><strong>Notes to send: </strong></p>
          <p>
            <%= consultation.notes_to_send %>
          </p>
        </div>
        <hr>
      </div>
    <% end %>
  </div>
  <% end %>
</div>